### ISSUE TITLE
TuckER 是发表在ICML2019上吗？

### ISSUE THREAD

**Issue by zq0x7a0x71** [thunlp/KRLPapers#8]
TuckER: Tensor Factorization for Knowledge Graph Completion. Ivana Balazˇevic ́, Carl Allen, Timothy M. Hospedales.

上述文章在 ICML2019 的 accepted paper （https://icml.cc/Conferences/2019/Schedule?type=Poster ）里没有找到，请确认下是否有误，谢谢！

**Comment by davidlvxin** [comment]
感谢指正，目前该论文还是放在arxiv上，已经修正了。
